package providers

import (
	"encoding/xml"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"github.com/AvengeMedia/DankMaterialShell/core/internal/keybinds"
)

const (
	labwcManagedBegin = "<!-- CyShell managed keybinds: begin -->"
	labwcManagedEnd   = "<!-- CyShell managed keybinds: end -->"
)

type LabwcProvider struct {
	configPath string
}

type labwcDocument struct {
	Keyboard labwcKeyboard `xml:"keyboard"`
}

type labwcKeyboard struct {
	Keybinds []labwcXMLKeybind `xml:"keybind"`
}

type labwcXMLKeybind struct {
	XMLName            xml.Name         `xml:"keybind"`
	Key                string           `xml:"key,attr"`
	OnRelease          string           `xml:"onRelease,attr,omitempty"`
	AllowWhenLocked    string           `xml:"allowWhenLocked,attr,omitempty"`
	OverrideInhibition string           `xml:"overrideInhibition,attr,omitempty"`
	Actions            []labwcXMLAction `xml:"action"`
}

type labwcXMLAction struct {
	XMLName     xml.Name `xml:"action"`
	Name        string   `xml:"name,attr"`
	Command     string   `xml:"command,attr,omitempty"`
	Direction   string   `xml:"direction,attr,omitempty"`
	SnapWindows string   `xml:"snapWindows,attr,omitempty"`
	Combine     string   `xml:"combine,attr,omitempty"`
	Region      string   `xml:"region,attr,omitempty"`
	To          string   `xml:"to,attr,omitempty"`
	Wrap        string   `xml:"wrap,attr,omitempty"`
	Toggle      string   `xml:"toggle,attr,omitempty"`
	Follow      string   `xml:"follow,attr,omitempty"`
	Output      string   `xml:"output,attr,omitempty"`
	Workspace   string   `xml:"workspace,attr,omitempty"`
	Identifier  string   `xml:"identifier,attr,omitempty"`
	Menu        string   `xml:"menu,attr,omitempty"`
	Policy      string   `xml:"policy,attr,omitempty"`
	X           string   `xml:"x,attr,omitempty"`
	Y           string   `xml:"y,attr,omitempty"`
	Width       string   `xml:"width,attr,omitempty"`
	Height      string   `xml:"height,attr,omitempty"`
	Decorations string   `xml:"decorations,attr,omitempty"`
	ForceSSD    string   `xml:"forceSSD,attr,omitempty"`
	OutputName  string   `xml:"output_name,attr,omitempty"`
}

type managedLabwcBind struct {
	Key         string
	Action      string
	Description string
	Options     map[string]any
}

func NewLabwcProvider(configPath string) *LabwcProvider {
	return &LabwcProvider{configPath: resolveLabwcConfigPath(configPath)}
}

func resolveLabwcConfigPath(path string) string {
	path = strings.TrimSpace(path)
	if path == "" {
		configDir, err := os.UserConfigDir()
		if err != nil || configDir == "" {
			return ""
		}
		return filepath.Join(configDir, "labwc", "rc.xml")
	}
	path = filepath.Clean(path)
	if strings.EqualFold(filepath.Ext(path), ".xml") {
		return path
	}
	return filepath.Join(path, "rc.xml")
}

func (p *LabwcProvider) Name() string { return "labwc" }

func (p *LabwcProvider) GetOverridePath() string {
	if p == nil {
		return ""
	}
	return p.configPath
}

func (p *LabwcProvider) GetCheatSheet() (*keybinds.CheatSheet, error) {
	if p == nil || p.configPath == "" {
		return nil, errors.New("labwc config path is unavailable")
	}
	data, err := os.ReadFile(p.configPath)
	if err != nil {
		return nil, fmt.Errorf("read labwc config: %w", err)
	}
	var doc labwcDocument
	if err := xml.Unmarshal(data, &doc); err != nil {
		return nil, fmt.Errorf("parse labwc config: %w", err)
	}
	managed, _ := parseManagedLabwcBinds(string(data))
	baseKeys, _ := labwcBaseKeySet(string(data))

	// Labwc applies later duplicate keybinds as overrides. Keep only the effective
	// binding so Settings does not show the original and CyShell override twice.
	type effectiveBind struct {
		bind  labwcXMLKeybind
		index int
	}
	effective := map[string]effectiveBind{}
	order := []string{}
	for index, bind := range doc.Keyboard.Keybinds {
		key := labwcKeyToGeneric(bind.Key)
		normalized := normalizeLabwcKey(key)
		if normalized == "" {
			continue
		}
		if _, exists := effective[normalized]; !exists {
			order = append(order, normalized)
		}
		effective[normalized] = effectiveBind{bind: bind, index: index}
	}
	sort.SliceStable(order, func(i, j int) bool {
		return effective[order[i]].index < effective[order[j]].index
	})

	categorized := map[string][]keybinds.Keybind{}
	for _, normalized := range order {
		bind := effective[normalized].bind
		action := canonicalLabwcActions(bind.Actions)
		if action == "" || strings.EqualFold(strings.TrimSpace(action), "None") {
			continue
		}
		desc := labwcAutogenerateDescription(action)
		source := "config"
		if override, ok := managed[normalized]; ok {
			source = "dms"
			if override.Description != "" {
				desc = override.Description
			}
		}
		allowInhibiting := !yesValue(bind.OverrideInhibition)
		categorized[categorizeLabwcAction(action)] = append(categorized[categorizeLabwcAction(action)], keybinds.Keybind{
			Key:             labwcKeyToGeneric(bind.Key),
			Description:     desc,
			Action:          action,
			Source:          source,
			AllowWhenLocked: yesValue(bind.AllowWhenLocked),
			AllowInhibiting: &allowInhibiting,
			Flags:           labwcFlags(bind),
			HasDefault:      source == "dms" && baseKeys[normalized],
		})
	}

	return &keybinds.CheatSheet{
		Title:            "Labwc Keybinds",
		Provider:         p.Name(),
		Binds:            categorized,
		DMSBindsIncluded: true,
	}, nil
}

func yesValue(value string) bool {
	switch strings.ToLower(strings.TrimSpace(value)) {
	case "yes", "true", "1", "on":
		return true
	default:
		return false
	}
}

func labwcFlags(bind labwcXMLKeybind) string {
	if yesValue(bind.OnRelease) {
		return "r"
	}
	return ""
}

func canonicalLabwcActions(actions []labwcXMLAction) string {
	parts := make([]string, 0, len(actions))
	for _, action := range actions {
		if canonical := canonicalLabwcAction(action); canonical != "" {
			parts = append(parts, canonical)
		}
	}
	return strings.Join(parts, " ; ")
}

func canonicalLabwcAction(action labwcXMLAction) string {
	name := strings.TrimSpace(action.Name)
	if name == "" {
		return ""
	}
	if strings.EqualFold(name, "Execute") {
		command := strings.TrimSpace(action.Command)
		if command == "" {
			return "spawn"
		}
		return "spawn " + command
	}

	value := ""
	switch strings.ToLower(name) {
	case "movetoedge", "resize", "growtoedge", "shrinktoedge", "togglesnaptoedge", "snaptoedge":
		value = action.Direction
	case "togglesnaptoregion", "snaptoregion":
		value = action.Region
	case "gotodesktop", "sendtodesktop":
		value = action.To
	case "focusoutput", "movetooutput":
		if action.Output != "" {
			value = action.Output
		} else {
			value = action.Direction
		}
	case "togglemaximize", "maximize", "unmaximize":
		value = action.Direction
	case "showmenu":
		value = action.Menu
	case "autoplace":
		value = action.Policy
	case "virtualoutputadd", "virtualoutputremove":
		value = action.OutputName
	case "moveto", "moverelative":
		if action.X != "" || action.Y != "" {
			value = action.X + "," + action.Y
		}
	case "resizeto":
		if action.Width != "" || action.Height != "" {
			value = action.Width + "x" + action.Height
		}
	case "setdecorations":
		value = action.Decorations
	}

	parts := []string{name}
	if strings.TrimSpace(value) != "" {
		parts = append(parts, strings.TrimSpace(value))
	}
	for _, option := range labwcExtraActionOptions(action, strings.ToLower(name)) {
		parts = append(parts, option)
	}
	return strings.Join(parts, " ")
}

func labwcExtraActionOptions(action labwcXMLAction, name string) []string {
	out := []string{}
	appendOption := func(key, value string) {
		if strings.TrimSpace(value) != "" {
			out = append(out, key+"="+strings.TrimSpace(value))
		}
	}
	appendOption("combine", action.Combine)
	appendOption("snapWindows", action.SnapWindows)
	appendOption("wrap", action.Wrap)
	appendOption("toggle", action.Toggle)
	appendOption("follow", action.Follow)
	appendOption("workspace", action.Workspace)
	appendOption("identifier", action.Identifier)
	appendOption("forceSSD", action.ForceSSD)
	if name != "setdecorations" {
		appendOption("decorations", action.Decorations)
	}
	return out
}

func categorizeLabwcAction(action string) string {
	fields := strings.Fields(action)
	if len(fields) == 0 {
		return "Other"
	}
	base := strings.ToLower(fields[0])
	switch base {
	case "nextwindow", "previouswindow", "nextwindowimmediate", "previouswindowimmediate":
		return "Alt-Tab"
	case "gotodesktop", "sendtodesktop":
		return "Workspace"
	case "focusoutput", "movetooutput":
		return "Monitor"
	case "reconfigure", "exit", "toggleshowdesktop", "togglekeybinds", "togglemagnify", "zoomin", "zoomout", "virtualoutputadd", "virtualoutputremove", "showmenu":
		return "System"
	case "close", "kill", "focus", "unfocus", "raise", "lower", "iconify", "move", "movetoedge", "resize", "resizerelative", "growtoedge", "shrinktoedge", "moveto", "resizeto", "moverelative", "togglesnaptoedge", "snaptoedge", "togglesnaptoregion", "snaptoregion", "unsnap", "setdecorations", "toggledecorations", "togglefullscreen", "togglemaximize", "maximize", "unmaximize", "togglealwaysontop", "togglealwaysonbottom", "toggleomnipresent", "autoplace", "shade", "unshade", "toggleshade":
		return "Window"
	default:
		if strings.HasPrefix(action, "spawn ") {
			return "Execute"
		}
		return "Other"
	}
}

func labwcAutogenerateDescription(action string) string {
	if strings.HasPrefix(action, "spawn ") {
		return strings.TrimPrefix(action, "spawn ")
	}
	fields := strings.Fields(action)
	if len(fields) == 0 {
		return action
	}
	labels := map[string]string{
		"Close": "Close window", "Iconify": "Minimize window", "ToggleFullscreen": "Toggle fullscreen",
		"ToggleMaximize": "Toggle maximize", "ToggleAlwaysOnTop": "Toggle always on top",
		"ToggleOmnipresent": "Toggle sticky window", "ToggleDecorations": "Toggle decorations",
		"GoToDesktop": "Switch workspace", "SendToDesktop": "Move window to workspace",
		"FocusOutput": "Focus output", "MoveToOutput": "Move window to output",
		"NextWindow": "Next window", "PreviousWindow": "Previous window",
		"ToggleShowDesktop": "Show desktop", "Reconfigure": "Reload Labwc configuration", "Exit": "Exit Labwc",
	}
	label := labels[fields[0]]
	if label == "" {
		return action
	}
	if len(fields) > 1 && !strings.Contains(fields[1], "=") {
		return label + " " + fields[1]
	}
	return label
}

func (p *LabwcProvider) SetBind(key, action, description string, options map[string]any) error {
	if p == nil || p.configPath == "" {
		return errors.New("labwc config path is unavailable")
	}
	key = normalizeGenericLabwcKey(key)
	if key == "" {
		return errors.New("key cannot be empty")
	}
	if strings.Contains(action, " ; ") {
		return errors.New("editing a multi-action Labwc binding requires replacing it with one action")
	}
	if _, err := labwcActionFromString(action); err != nil {
		return err
	}
	binds, err := p.loadManagedBinds()
	if err != nil {
		return err
	}
	binds[normalizeLabwcKey(key)] = managedLabwcBind{
		Key:         key,
		Action:      strings.TrimSpace(action),
		Description: strings.TrimSpace(description),
		Options:     cloneAnyMap(options),
	}
	return p.writeManagedBinds(binds)
}

func (p *LabwcProvider) ReplaceBind(originalKey, key, action, description string, options map[string]any) error {
	if p == nil || p.configPath == "" {
		return errors.New("labwc config path is unavailable")
	}
	originalKey = normalizeGenericLabwcKey(originalKey)
	key = normalizeGenericLabwcKey(key)
	if originalKey == "" || key == "" {
		return errors.New("original and replacement keys are required")
	}
	if normalizeLabwcKey(originalKey) == normalizeLabwcKey(key) {
		return p.SetBind(key, action, description, options)
	}
	if strings.Contains(action, " ; ") {
		return errors.New("editing a multi-action Labwc binding requires replacing it with one action")
	}
	if _, err := labwcActionFromString(action); err != nil {
		return err
	}
	binds, err := p.loadManagedBinds()
	if err != nil {
		return err
	}
	baseKeys, err := p.baseKeySet()
	if err != nil {
		return err
	}
	oldNormalized := normalizeLabwcKey(originalKey)
	if baseKeys[oldNormalized] {
		// A later None binding disables the original rc.xml shortcut without
		// rewriting the user's config. It remains resettable via the CLI.
		binds[oldNormalized] = managedLabwcBind{
			Key:         originalKey,
			Action:      "None",
			Description: "Disabled after moving shortcut",
			Options:     map[string]any{},
		}
	} else {
		delete(binds, oldNormalized)
	}
	binds[normalizeLabwcKey(key)] = managedLabwcBind{
		Key:         key,
		Action:      strings.TrimSpace(action),
		Description: strings.TrimSpace(description),
		Options:     cloneAnyMap(options),
	}
	return p.writeManagedBinds(binds)
}

func (p *LabwcProvider) RemoveBind(key string) error {
	if p == nil || p.configPath == "" {
		return errors.New("labwc config path is unavailable")
	}
	if _, err := os.Stat(p.configPath); os.IsNotExist(err) {
		return nil
	}
	binds, err := p.loadManagedBinds()
	if err != nil {
		return err
	}
	delete(binds, normalizeLabwcKey(key))
	return p.writeManagedBinds(binds)
}

func (p *LabwcProvider) ResetBind(key string) error { return p.RemoveBind(key) }

func cloneAnyMap(source map[string]any) map[string]any {
	out := map[string]any{}
	for key, value := range source {
		out[key] = value
	}
	return out
}

func (p *LabwcProvider) baseKeySet() (map[string]bool, error) {
	data, err := os.ReadFile(p.configPath)
	if err != nil {
		return nil, fmt.Errorf("read labwc config: %w", err)
	}
	return labwcBaseKeySet(string(data))
}

func labwcBaseKeySet(content string) (map[string]bool, error) {
	cleaned, err := removeManagedLabwcBlock(content)
	if err != nil {
		return nil, err
	}
	var doc labwcDocument
	if err := xml.Unmarshal([]byte(cleaned), &doc); err != nil {
		return nil, fmt.Errorf("parse base labwc config: %w", err)
	}
	keys := map[string]bool{}
	for _, bind := range doc.Keyboard.Keybinds {
		key := normalizeLabwcKey(labwcKeyToGeneric(bind.Key))
		if key != "" {
			keys[key] = true
		}
	}
	return keys, nil
}

func removeManagedLabwcBlock(content string) (string, error) {
	start := strings.Index(content, labwcManagedBegin)
	if start < 0 {
		return content, nil
	}
	lineStart := strings.LastIndex(content[:start], "\n") + 1
	endRel := strings.Index(content[start:], labwcManagedEnd)
	if endRel < 0 {
		return "", errors.New("Labwc config has a CyShell begin marker without an end marker")
	}
	end := start + endRel + len(labwcManagedEnd)
	return content[:lineStart] + content[end:], nil
}

func (p *LabwcProvider) loadManagedBinds() (map[string]managedLabwcBind, error) {
	data, err := os.ReadFile(p.configPath)
	if os.IsNotExist(err) {
		return map[string]managedLabwcBind{}, nil
	}
	if err != nil {
		return nil, fmt.Errorf("read labwc config: %w", err)
	}
	return parseManagedLabwcBinds(string(data))
}

func parseManagedLabwcBinds(content string) (map[string]managedLabwcBind, error) {
	result := map[string]managedLabwcBind{}
	body, ok := labwcManagedBody(content)
	if !ok || strings.TrimSpace(body) == "" {
		return result, nil
	}
	decoder := xml.NewDecoder(strings.NewReader("<keyboard>" + body + "</keyboard>"))
	pendingDescription := ""
	for {
		token, err := decoder.Token()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return nil, fmt.Errorf("parse CyShell Labwc keybind block: %w", err)
		}
		switch token := token.(type) {
		case xml.Comment:
			if desc, ok := strings.CutPrefix(strings.TrimSpace(string(token)), "CyShell: "); ok {
				pendingDescription = strings.TrimSpace(desc)
			}
		case xml.StartElement:
			if token.Name.Local != "keybind" {
				continue
			}
			var bind labwcXMLKeybind
			if err := decoder.DecodeElement(&bind, &token); err != nil {
				return nil, err
			}
			action := canonicalLabwcActions(bind.Actions)
			if action == "" {
				continue
			}
			allowInhibiting := !yesValue(bind.OverrideInhibition)
			key := labwcKeyToGeneric(bind.Key)
			result[normalizeLabwcKey(key)] = managedLabwcBind{
				Key:         key,
				Action:      action,
				Description: pendingDescription,
				Options: map[string]any{
					"allow-when-locked": yesValue(bind.AllowWhenLocked),
					"allow-inhibiting":  allowInhibiting,
					"flags":             labwcFlags(bind),
				},
			}
			pendingDescription = ""
		}
	}
	return result, nil
}

func labwcManagedBody(content string) (string, bool) {
	start := strings.Index(content, labwcManagedBegin)
	if start < 0 {
		return "", false
	}
	start += len(labwcManagedBegin)
	endRel := strings.Index(content[start:], labwcManagedEnd)
	if endRel < 0 {
		return "", false
	}
	return content[start : start+endRel], true
}

func (p *LabwcProvider) writeManagedBinds(binds map[string]managedLabwcBind) error {
	if err := os.MkdirAll(filepath.Dir(p.configPath), 0o755); err != nil {
		return fmt.Errorf("create labwc config directory: %w", err)
	}
	data, err := os.ReadFile(p.configPath)
	if os.IsNotExist(err) {
		data = []byte("<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<labwc_config>\n  <keyboard>\n  </keyboard>\n</labwc_config>\n")
	} else if err != nil {
		return fmt.Errorf("read labwc config: %w", err)
	}
	block, err := renderManagedLabwcBlock(binds)
	if err != nil {
		return err
	}
	updated, err := replaceManagedLabwcBlock(string(data), block)
	if err != nil {
		return err
	}
	var validation labwcDocument
	if err := xml.Unmarshal([]byte(updated), &validation); err != nil {
		return fmt.Errorf("refuse to write invalid labwc config: %w", err)
	}

	mode := os.FileMode(0o644)
	if stat, statErr := os.Stat(p.configPath); statErr == nil {
		mode = stat.Mode().Perm()
	}
	tmp := p.configPath + ".cyshell.tmp"
	if err := os.WriteFile(tmp, []byte(updated), mode); err != nil {
		return fmt.Errorf("write labwc config temp file: %w", err)
	}
	if err := os.Chmod(tmp, mode); err != nil {
		_ = os.Remove(tmp)
		return err
	}
	if err := os.Rename(tmp, p.configPath); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("replace labwc config: %w", err)
	}
	return nil
}

func renderManagedLabwcBlock(binds map[string]managedLabwcBind) (string, error) {
	keys := make([]string, 0, len(binds))
	for key := range binds {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	var builder strings.Builder
	builder.WriteString("    " + labwcManagedBegin + "\n")
	for _, normalized := range keys {
		managed := binds[normalized]
		action, err := labwcActionFromString(managed.Action)
		if err != nil {
			return "", err
		}
		bind := labwcXMLKeybind{Key: genericKeyToLabwc(managed.Key), Actions: []labwcXMLAction{action}}
		if value, _ := managed.Options["allow-when-locked"].(bool); value {
			bind.AllowWhenLocked = "yes"
		}
		if value, exists := managed.Options["allow-inhibiting"].(bool); exists && !value {
			bind.OverrideInhibition = "yes"
		}
		if flags, _ := managed.Options["flags"].(string); strings.Contains(flags, "r") {
			bind.OnRelease = "yes"
		}
		if flags, _ := managed.Options["flags"].(string); strings.Contains(flags, "l") {
			bind.AllowWhenLocked = "yes"
		}
		if desc := sanitizeXMLComment(managed.Description); desc != "" {
			builder.WriteString("    <!-- CyShell: " + desc + " -->\n")
		}
		xmlData, err := xml.MarshalIndent(bind, "    ", "  ")
		if err != nil {
			return "", err
		}
		builder.Write(xmlData)
		builder.WriteByte('\n')
	}
	builder.WriteString("    " + labwcManagedEnd)
	return builder.String(), nil
}

func sanitizeXMLComment(value string) string {
	value = strings.Join(strings.Fields(value), " ")
	value = strings.ReplaceAll(value, "--", "—")
	if strings.HasSuffix(value, "-") {
		value = strings.TrimSuffix(value, "-") + "—"
	}
	return strings.TrimSpace(value)
}

func replaceManagedLabwcBlock(content, block string) (string, error) {
	start := strings.Index(content, labwcManagedBegin)
	if start >= 0 {
		lineStart := strings.LastIndex(content[:start], "\n") + 1
		endRel := strings.Index(content[start:], labwcManagedEnd)
		if endRel < 0 {
			return "", errors.New("Labwc config has a CyShell begin marker without an end marker")
		}
		end := start + endRel + len(labwcManagedEnd)
		return content[:lineStart] + block + content[end:], nil
	}

	lower := strings.ToLower(content)
	if keyboardEnd := strings.LastIndex(lower, "</keyboard>"); keyboardEnd >= 0 {
		prefix := content[:keyboardEnd]
		if !strings.HasSuffix(prefix, "\n") {
			prefix += "\n"
		}
		return prefix + block + "\n  " + content[keyboardEnd:], nil
	}
	rootEnd := strings.LastIndex(lower, "</labwc_config>")
	if rootEnd < 0 {
		return "", errors.New("Labwc config is missing </labwc_config>")
	}
	prefix := content[:rootEnd]
	if !strings.HasSuffix(prefix, "\n") {
		prefix += "\n"
	}
	return prefix + "  <keyboard>\n" + block + "\n  </keyboard>\n" + content[rootEnd:], nil
}

func labwcActionFromString(raw string) (labwcXMLAction, error) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return labwcXMLAction{}, errors.New("action cannot be empty")
	}
	if strings.HasPrefix(raw, "spawn ") {
		command := strings.TrimSpace(strings.TrimPrefix(raw, "spawn "))
		if command == "" {
			return labwcXMLAction{}, errors.New("spawn command requires arguments")
		}
		return labwcXMLAction{Name: "Execute", Command: command}, nil
	}
	fields := strings.Fields(raw)
	if len(fields) == 0 || !validLabwcActionName(fields[0]) {
		return labwcXMLAction{}, fmt.Errorf("invalid Labwc action %q", raw)
	}
	action := labwcXMLAction{Name: fields[0]}
	positional := ""
	for _, field := range fields[1:] {
		if key, value, ok := strings.Cut(field, "="); ok {
			setLabwcActionOption(&action, key, value)
			continue
		}
		if positional != "" {
			positional += " "
		}
		positional += field
	}
	if positional != "" {
		setLabwcPrimaryActionValue(&action, positional)
	}
	return action, nil
}

func validLabwcActionName(name string) bool {
	for _, r := range name {
		if !unicode.IsLetter(r) && !unicode.IsDigit(r) && r != '_' {
			return false
		}
	}
	return name != ""
}

func setLabwcPrimaryActionValue(action *labwcXMLAction, value string) {
	switch strings.ToLower(action.Name) {
	case "movetoedge", "resize", "growtoedge", "shrinktoedge", "togglesnaptoedge", "snaptoedge":
		action.Direction = value
	case "togglesnaptoregion", "snaptoregion":
		action.Region = value
	case "gotodesktop", "sendtodesktop":
		action.To = value
	case "focusoutput", "movetooutput":
		if isLabwcDirection(value) {
			action.Direction = value
		} else {
			action.Output = value
		}
	case "togglemaximize", "maximize", "unmaximize":
		action.Direction = value
	case "showmenu":
		action.Menu = value
	case "autoplace":
		action.Policy = value
	case "virtualoutputadd", "virtualoutputremove":
		action.OutputName = value
	case "moveto", "moverelative":
		parts := strings.SplitN(value, ",", 2)
		action.X = strings.TrimSpace(parts[0])
		if len(parts) == 2 {
			action.Y = strings.TrimSpace(parts[1])
		}
	case "resizeto":
		parts := strings.SplitN(value, "x", 2)
		action.Width = strings.TrimSpace(parts[0])
		if len(parts) == 2 {
			action.Height = strings.TrimSpace(parts[1])
		}
	case "setdecorations":
		action.Decorations = value
	}
}

func setLabwcActionOption(action *labwcXMLAction, key, value string) {
	switch strings.ToLower(strings.TrimSpace(key)) {
	case "direction":
		action.Direction = value
	case "snapwindows":
		action.SnapWindows = value
	case "combine":
		action.Combine = value
	case "region":
		action.Region = value
	case "to":
		action.To = value
	case "wrap":
		action.Wrap = value
	case "toggle":
		action.Toggle = value
	case "follow":
		action.Follow = value
	case "output":
		action.Output = value
	case "workspace":
		action.Workspace = value
	case "identifier":
		action.Identifier = value
	case "menu":
		action.Menu = value
	case "policy":
		action.Policy = value
	case "x":
		action.X = value
	case "y":
		action.Y = value
	case "width":
		action.Width = value
	case "height":
		action.Height = value
	case "decorations":
		action.Decorations = value
	case "forcessd":
		action.ForceSSD = value
	case "output_name":
		action.OutputName = value
	}
}

func isLabwcDirection(value string) bool {
	switch strings.ToLower(value) {
	case "left", "right", "up", "down", "up-left", "up-right", "down-left", "down-right", "center":
		return true
	default:
		return false
	}
}

func normalizeGenericLabwcKey(key string) string {
	key = strings.TrimSpace(key)
	if key == "" {
		return ""
	}
	if !strings.Contains(key, "+") {
		return labwcKeyToGeneric(key)
	}
	parts := strings.Split(key, "+")
	out := make([]string, 0, len(parts))
	for index, part := range parts {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		if index == len(parts)-1 {
			if len(part) == 1 && unicode.IsLetter(rune(part[0])) {
				part = strings.ToUpper(part)
			}
			out = append(out, part)
			continue
		}
		out = append(out, canonicalGenericModifier(part))
	}
	return strings.Join(out, "+")
}

func canonicalGenericModifier(value string) string {
	switch strings.ToLower(value) {
	case "w", "win", "super", "mod4", "mod":
		return "Super"
	case "a", "alt", "mod1":
		return "Alt"
	case "c", "ctrl", "control":
		return "Ctrl"
	case "s", "shift":
		return "Shift"
	case "h", "hyper", "mod3":
		return "Hyper"
	case "m", "meta", "mod5":
		return "Meta"
	default:
		return value
	}
}

func normalizeLabwcKey(key string) string {
	return strings.ToLower(strings.ReplaceAll(normalizeGenericLabwcKey(key), " ", ""))
}

func labwcKeyToGeneric(key string) string {
	key = strings.TrimSpace(key)
	if key == "" || !strings.Contains(key, "-") {
		return key
	}
	parts := strings.Split(key, "-")
	mods := []string{}
	index := 0
	for index < len(parts)-1 {
		switch strings.ToLower(parts[index]) {
		case "w", "mod4":
			mods = append(mods, "Super")
		case "a", "mod1":
			mods = append(mods, "Alt")
		case "c":
			mods = append(mods, "Ctrl")
		case "s":
			mods = append(mods, "Shift")
		case "h", "mod3":
			mods = append(mods, "Hyper")
		case "m", "mod5":
			mods = append(mods, "Meta")
		default:
			return key
		}
		index++
	}
	keyPart := strings.Join(parts[index:], "-")
	if len(keyPart) == 1 && unicode.IsLetter(rune(keyPart[0])) {
		keyPart = strings.ToUpper(keyPart)
	}
	mods = append(mods, keyPart)
	return strings.Join(mods, "+")
}

func genericKeyToLabwc(key string) string {
	key = normalizeGenericLabwcKey(key)
	if !strings.Contains(key, "+") {
		return key
	}
	parts := strings.Split(key, "+")
	out := make([]string, 0, len(parts))
	for index, part := range parts {
		if index == len(parts)-1 {
			if len(part) == 1 && unicode.IsLetter(rune(part[0])) {
				part = strings.ToLower(part)
			}
			out = append(out, part)
			continue
		}
		switch strings.ToLower(part) {
		case "super", "win", "mod", "mod4":
			out = append(out, "W")
		case "alt", "mod1":
			out = append(out, "A")
		case "ctrl", "control":
			out = append(out, "C")
		case "shift":
			out = append(out, "S")
		case "hyper", "mod3":
			out = append(out, "H")
		case "meta", "mod5":
			out = append(out, "M")
		default:
			out = append(out, part)
		}
	}
	return strings.Join(out, "-")
}
